spring.application.name=energy-api
server.port=8091

# Database Connection
spring.datasource.url=jdbc:postgresql://localhost:5432/disysuser
spring.datasource.username=disysuser
spring.datasource.password=disyspw

# Hibernate Configuration
spring.jpa.hibernate.ddl-auto=validate