spring.application.name=usage-service
server.port=8092

# Database Connection (Matches your docker-compose.yml)
spring.datasource.url=jdbc:postgresql://localhost:5432/disysuser
spring.datasource.username=disysuser
spring.datasource.password=disyspw

# Hibernate/JPA Configuration
# "validate" ensures your Java code matches the tables we built via init.sql
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true